name: SendNotificationToSlack

on:
  push:
    branches:
    - master
    - release/*
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  my_job:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 8.11.1

    - name: Install Dependencies
      run: |
        npm install 

        
  slack:
    
    runs-on: ubuntu-latest
    
    steps:
     - name: Slatify
       uses: homoluctus/slatify@v2.0.1
       with:
         type: 'success'
         job_name: 'slack'
         url: 'https://hooks.slack.com/services/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'
         channel: '#general'
         commit: true
