name: SendNotificationToSlack

on:
  push:
    branches:
      - master
      - release/*

jobs:

#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: Run a one-line script
#        run: echo Hello, world!
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
#
#  my_job:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: Setup Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: 8.11.1
#
#      - name: Install Dependencies
#        run: |
#          npm install


  slack_notification:

    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: '#3278BD'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: 'Uploaded a version to the google play store :rocket:'
          SLACK_USERNAME: MOVEO
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEB_HOOK }}