name: SendNotificationToSlack

on:
  push:
    branches:
    - master
    - release/*
    
jobs:

  my_job:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Dependencies
      run: |
        npm install 
        
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
  slack:
    
    runs-on: ubuntu-18.04
    
    steps:
     - name: Slatify
       uses: homoluctus/slatify@v2.0.1
       with:
         type: success
         job_name: slack
         username: Tamara Shlomov 
         url: moveo-bravo.slack.com
         commit: true
         token:  "" 
