name: Upload app to Google Play Store

on:
  push:
    branches:
      - master

jobs:

  create_release_apk:

    runs-on: ubuntu-latest

    steps:
#      - name: create release apk
#        uses: r0adkll/sign-android-release@v1
#        with:
##          releaseDirectory: /app/build/outputs/apk/release
#          releaseDirectory: /app/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY }}



      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - run: npm i

      - name: echo files
        run: |
          ls /$GITHUB_WORKSPACE
          test -f /$GITHUB_WORKSPACE/app-release.apk && echo "I am exist"
          test -f /home/runner/work/Github-Action-Test/Github-Action-Test/app/release/app-release.apk && echo "I should not print"
          test -f /home/runner/work/Github-Action-Test/Github-Action-Test/app-release.apk && echo "I am existing again"

      - name: upload apk
        uses: ./.github/actions/upload-apk
        id: apk

      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.0.2
        with:
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: il.co.moveo.github_action_test
          releaseFile: ${{ github.workspace }}/app-release.apk
          track: production
          userFraction: 0.5




  #          alias: ${{ secrets.ALIAS }}
  #          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
  #          keyPassword: ${{ secrets.KEY_PASSWORD }}

  #          releaseFile: /app/build/outputs/apk/release/app-release.apk
  #          track: production
  #         userFraction: 1
  #         whatsNewDirectory: /distribution/whatsnew
  #         mappingFile: /app/build/outputs/mapping/release/mapping.txt
