name: Upload app to Google Play Store

on:
  push:
    branches:
      - master

jobs:
  upload_to_store:

    runs-on: ubuntu-latest

    steps:
    - name: Upload Android Release to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ SERVICE_ACCOUNT_JSON }}
        packageName: il.co.moveo.github_action_test
        releaseFile: .apk
#         track: production
#         userFraction: 1
#         whatsNewDirectory: /distribution/whatsnew
#         mappingFile: /app/build/outputs/mapping/release/mapping.txt
